name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20' # adapte selon ta version Node

      - name: Install dependencies
        run: npm ci

      - name: Run ESLint
        run: yarn lint

      - name: Run Prettier check
        run: yarn prettier -c .

      - name: Build Next.js
        run: yarn build

